# Generated by Django 3.1.5 on 2021-02-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(upload_to='products/')),
                ('price', models.PositiveIntegerField()),
                ('marked_price', models.PositiveIntegerField(default=False)),
                ('description', models.TextField()),
                ('warranty', models.CharField(blank=True, max_length=350, null=True)),
                ('return_policy', models.CharField(blank=True, max_length=350, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
