# Generated by Django 3.1.5 on 2021-02-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='selling_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='marked_price',
            field=models.PositiveIntegerField(),
        ),
    ]
