# Generated by Django 3.1.5 on 2021-02-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210203_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='marked_price',
            field=models.PositiveIntegerField(default=False, null=True),
        ),
    ]
